openapi: 3.0.3
info: 
  title: Ping Pong
  version: 99.99.0
servers: 
  - url : https://localhost:800
path: 
  /ping: 
    get: 
      responses: 
        200: 
          description: pong
          content: 
            text/plain: 
              schema: 
                type: string
                example: pong 
