openapi: 3.0.3
info: 
  title: Gestion de tâches
  version: 99.99.0
servers: 
  - url : https://localhost:800
paths: 
  /tasks: 
    get: 
      responses: 
        description: retourne une liste de tâches
        content: 
          application/json: 
            schema: 
              type: array
              example: 
               $ref: '#/components/schemas/Task'
    post: 
      responses: 
        201: 

components: 
  shemas: 
    Task: 
      type: object
      properties: 
        id: 
          type: integer
          example: 1
        title: 
          type: string
          example: "Faire les courses"
        completed: 
          type: boolean
          example: false