openapi: 3.0.3
info: 
  title:  Evenemenent API 
  version:  99.99.0
components:
  shemas: 
    EventModel: 
      type: object
      properties:
        name: 
          type: string
        description:
          type: string
        start_date:
          type: string
        end_date: 
          type: string
      required: 
        -name
        -description
        -start_date
        -end_date
            
